interface IoTSensor {
  id: string;
  type: 'air_quality' | 'noise_level' | 'traffic_flow' | 'water_level' | 'waste_bin' | 'street_light' | 'weather' | 'parking' | 'crowd_density';
  name: string;
  location: {
    lat: number;
    lng: number;
    address: string;
    zone: string;
  };
  status: 'active' | 'inactive' | 'maintenance' | 'error';
  lastReading: Date;
  batteryLevel?: number;
  signalStrength: number;
  manufacturer: string;
  model: string;
  installDate: Date;
  calibrationDate?: Date;
  thresholds: {
    warning: number;
    critical: number;
    unit: string;
  };
}

interface SensorReading {
  sensorId: string;
  timestamp: Date;
  value: number;
  unit: string;
  quality: 'good' | 'fair' | 'poor';
  metadata?: {
    temperature?: number;
    humidity?: number;
    batteryLevel?: number;
    rssi?: number;
  };
}

interface IoTAlert {
  id: string;
  sensorId: string;
  sensor: IoTSensor;
  type: 'threshold_exceeded' | 'sensor_offline' | 'low_battery' | 'maintenance_required' | 'anomaly_detected';
  severity: 'low' | 'medium' | 'high' | 'critical';
  title: string;
  description: string;
  reading?: SensorReading;
  createdAt: Date;
  resolvedAt?: Date;
  autoGenerated: boolean;
  reportId?: string; // If automatically created a civic report
}

interface SmartCityDashboard {
  airQualityIndex: number;
  noiseLevel: number;
  trafficFlow: number;
  waterLevels: number[];
  wasteCapacity: number;
  streetLightStatus: number;
  weatherData: {
    temperature: number;
    humidity: number;
    windSpeed: number;
    rainfall: number;
  };
  alerts: IoTAlert[];
  sensorHealth: {
    active: number;
    inactive: number;
    maintenance: number;
    total: number;
  };
}

interface PredictiveModel {
  sensorType: string;
  algorithm: 'linear_regression' | 'arima' | 'neural_network' | 'random_forest';
  accuracy: number;
  lastTrained: Date;
  features: string[];
  predictions: {
    nextHour: number;
    next6Hours: number;
    next24Hours: number;
    confidence: number;
  };
}

export class IoTIntegrationService {
  private sensors: Map<string, IoTSensor> = new Map();
  private readings: Map<string, SensorReading[]> = new Map();
  private alerts: IoTAlert[] = [];
  private predictiveModels: Map<string, PredictiveModel> = new Map();
  private isConnected = false;
  private websocket: WebSocket | null = null;

  constructor() {
    this.initializeDemoSensors();
    this.initializePredictiveModels();
    this.startDataSimulation();
  }

  private initializeDemoSensors() {
    const demoSensors: IoTSensor[] = [
      // Air Quality Sensors
      {
        id: 'aq_001',
        type: 'air_quality',
        name: 'Central Park Air Quality Monitor',
        location: { lat: 23.2599, lng: 77.4126, address: 'Central Park, Bhopal', zone: 'Zone-A' },
        status: 'active',
        lastReading: new Date(),
        batteryLevel: 85,
        signalStrength: -45,
        manufacturer: 'SensorTech',
        model: 'AQ-300',
        installDate: new Date('2024-01-15'),
        thresholds: { warning: 100, critical: 200, unit: 'AQI' }
      },
      {
        id: 'aq_002',
        type: 'air_quality',
        name: 'Industrial Area AQ Monitor',
        location: { lat: 23.2456, lng: 77.3912, address: 'Industrial Area, Bhopal', zone: 'Zone-B' },
        status: 'active',
        lastReading: new Date(),
        batteryLevel: 62,
        signalStrength: -52,
        manufacturer: 'SensorTech',
        model: 'AQ-300',
        installDate: new Date('2024-02-01'),
        thresholds: { warning: 100, critical: 200, unit: 'AQI' }
      },

      // Noise Level Sensors
      {
        id: 'nl_001',
        type: 'noise_level',
        name: 'Main Road Noise Monitor',
        location: { lat: 23.2728, lng: 77.4081, address: 'MP Nagar, Bhopal', zone: 'Zone-A' },
        status: 'active',
        lastReading: new Date(),
        batteryLevel: 78,
        signalStrength: -48,
        manufacturer: 'AcousticSense',
        model: 'NS-150',
        installDate: new Date('2024-01-20'),
        thresholds: { warning: 70, critical: 85, unit: 'dB' }
      },

      // Traffic Flow Sensors
      {
        id: 'tf_001',
        type: 'traffic_flow',
        name: 'Roshanpura Junction Traffic Counter',
        location: { lat: 23.2156, lng: 77.4304, address: 'Roshanpura Junction, Bhopal', zone: 'Zone-C' },
        status: 'active',
        lastReading: new Date(),
        signalStrength: -41,
        manufacturer: 'TrafficTech',
        model: 'TC-500',
        installDate: new Date('2024-01-10'),
        thresholds: { warning: 500, critical: 800, unit: 'vehicles/hour' }
      },

      // Waste Bin Sensors
      {
        id: 'wb_001',
        type: 'waste_bin',
        name: 'New Market Waste Monitor',
        location: { lat: 23.2699, lng: 77.4081, address: 'New Market, Bhopal', zone: 'Zone-A' },
        status: 'active',
        lastReading: new Date(),
        batteryLevel: 45,
        signalStrength: -55,
        manufacturer: 'SmartWaste',
        model: 'BM-200',
        installDate: new Date('2024-02-15'),
        thresholds: { warning: 80, critical: 95, unit: '%' }
      },
      {
        id: 'wb_002',
        type: 'waste_bin',
        name: 'TT Nagar Waste Monitor',
        location: { lat: 23.2420, lng: 77.3956, address: 'TT Nagar, Bhopal', zone: 'Zone-B' },
        status: 'maintenance',
        lastReading: new Date(Date.now() - 2 * 60 * 60 * 1000),
        batteryLevel: 12,
        signalStrength: -68,
        manufacturer: 'SmartWaste',
        model: 'BM-200',
        installDate: new Date('2024-01-25'),
        thresholds: { warning: 80, critical: 95, unit: '%' }
      },

      // Street Light Sensors
      {
        id: 'sl_001',
        type: 'street_light',
        name: 'Hamidia Road Light Control',
        location: { lat: 23.2649, lng: 77.4061, address: 'Hamidia Road, Bhopal', zone: 'Zone-A' },
        status: 'active',
        lastReading: new Date(),
        batteryLevel: 92,
        signalStrength: -42,
        manufacturer: 'SmartLight',
        model: 'SL-400',
        installDate: new Date('2024-01-05'),
        thresholds: { warning: 20, critical: 10, unit: '%' }
      },

      // Water Level Sensors
      {
        id: 'wl_001',
        type: 'water_level',
        name: 'Upper Lake Water Monitor',
        location: { lat: 23.2584, lng: 77.3803, address: 'Upper Lake, Bhopal', zone: 'Zone-D' },
        status: 'active',
        lastReading: new Date(),
        batteryLevel: 88,
        signalStrength: -50,
        manufacturer: 'HydroSense',
        model: 'WL-300',
        installDate: new Date('2023-12-20'),
        thresholds: { warning: 85, critical: 95, unit: '%' }
      }
    ];

    demoSensors.forEach(sensor => {
      this.sensors.set(sensor.id, sensor);
      this.readings.set(sensor.id, []);
    });
  }

  private initializePredictiveModels() {
    const models: PredictiveModel[] = [
      {
        sensorType: 'air_quality',
        algorithm: 'neural_network',
        accuracy: 0.87,
        lastTrained: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        features: ['temperature', 'humidity', 'wind_speed', 'traffic_density', 'industrial_activity'],
        predictions: { nextHour: 125, next6Hours: 135, next24Hours: 115, confidence: 0.87 }
      },
      {
        sensorType: 'traffic_flow',
        algorithm: 'arima',
        accuracy: 0.92,
        lastTrained: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        features: ['time_of_day', 'day_of_week', 'weather', 'events', 'historical_patterns'],
        predictions: { nextHour: 420, next6Hours: 380, next24Hours: 520, confidence: 0.92 }
      },
      {
        sensorType: 'waste_bin',
        algorithm: 'random_forest',
        accuracy: 0.89,
        lastTrained: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        features: ['collection_schedule', 'location_type', 'season', 'nearby_events', 'historical_fill_rate'],
        predictions: { nextHour: 85, next6Hours: 92, next24Hours: 95, confidence: 0.89 }
      }
    ];

    models.forEach(model => {
      this.predictiveModels.set(model.sensorType, model);
    });
  }

  private startDataSimulation() {
    // Simulate real-time sensor data
    setInterval(() => {
      this.simulateSensorReadings();
    }, 30000); // Every 30 seconds

    // Check for alerts
    setInterval(() => {
      this.checkAlerts();
    }, 60000); // Every minute
  }

  private simulateSensorReadings() {
    this.sensors.forEach((sensor, sensorId) => {
      if (sensor.status === 'active') {
        const reading = this.generateMockReading(sensor);
        this.addSensorReading(sensorId, reading);
      }
    });
  }

  private generateMockReading(sensor: IoTSensor): SensorReading {
    const now = new Date();
    let value: number;
    let quality: 'good' | 'fair' | 'poor' = 'good';

    // Generate realistic values based on sensor type
    switch (sensor.type) {
      case 'air_quality':
        value = 80 + Math.random() * 60 + (Math.sin(Date.now() / 10000) * 20); // 80-140 AQI
        if (value > 150) quality = 'poor';
        else if (value > 100) quality = 'fair';
        break;

      case 'noise_level':
        value = 60 + Math.random() * 25 + (Math.sin(Date.now() / 5000) * 10); // 60-85 dB
        if (value > 80) quality = 'poor';
        else if (value > 70) quality = 'fair';
        break;

      case 'traffic_flow':
        const hour = now.getHours();
        const baseTraffic = hour >= 8 && hour <= 10 || hour >= 17 && hour <= 19 ? 600 : 200;
        value = baseTraffic + Math.random() * 200; // Rush hour vs normal
        break;

      case 'waste_bin':
        value = Math.min(100, (sensor.lastReading ? 75 : 50) + Math.random() * 15); // Gradual fill
        if (value > 90) quality = 'poor';
        else if (value > 80) quality = 'fair';
        break;

      case 'street_light':
        value = Math.random() > 0.95 ? 0 : 100; // Occasional outage
        break;

      case 'water_level':
        value = 82 + Math.random() * 10 + Math.sin(Date.now() / 20000) * 5; // 82-92%
        break;

      default:
        value = Math.random() * 100;
    }

    return {
      sensorId: sensor.id,
      timestamp: now,
      value: Math.round(value * 100) / 100,
      unit: sensor.thresholds.unit,
      quality,
      metadata: {
        temperature: 25 + Math.random() * 10,
        humidity: 60 + Math.random() * 20,
        batteryLevel: sensor.batteryLevel,
        rssi: sensor.signalStrength
      }
    };
  }

  public addSensorReading(sensorId: string, reading: SensorReading) {
    const readings = this.readings.get(sensorId) || [];
    readings.push(reading);
    
    // Keep only last 1000 readings per sensor
    if (readings.length > 1000) {
      readings.splice(0, readings.length - 1000);
    }
    
    this.readings.set(sensorId, readings);
    
    // Update sensor last reading time
    const sensor = this.sensors.get(sensorId);
    if (sensor) {
      sensor.lastReading = reading.timestamp;
    }
  }

  private checkAlerts() {
    this.sensors.forEach((sensor, sensorId) => {
      const readings = this.readings.get(sensorId) || [];
      const latestReading = readings[readings.length - 1];
      
      if (!latestReading) return;

      // Check threshold alerts
      if (latestReading.value >= sensor.thresholds.critical) {
        this.createAlert(sensor, 'threshold_exceeded', 'critical', latestReading);
      } else if (latestReading.value >= sensor.thresholds.warning) {
        this.createAlert(sensor, 'threshold_exceeded', 'high', latestReading);
      }

      // Check sensor health alerts
      const timeSinceLastReading = Date.now() - sensor.lastReading.getTime();
      if (timeSinceLastReading > 10 * 60 * 1000) { // 10 minutes
        this.createAlert(sensor, 'sensor_offline', 'medium');
      }

      // Check battery alerts
      if (sensor.batteryLevel && sensor.batteryLevel < 20) {
        this.createAlert(sensor, 'low_battery', 'medium');
      }

      // Check maintenance alerts
      if (sensor.calibrationDate) {
        const daysSinceCalibration = (Date.now() - sensor.calibrationDate.getTime()) / (1000 * 60 * 60 * 24);
        if (daysSinceCalibration > 90) {
          this.createAlert(sensor, 'maintenance_required', 'low');
        }
      }
    });
  }

  private createAlert(sensor: IoTSensor, type: IoTAlert['type'], severity: IoTAlert['severity'], reading?: SensorReading) {
    // Check if similar alert already exists
    const existingAlert = this.alerts.find(alert => 
      alert.sensorId === sensor.id && 
      alert.type === type && 
      !alert.resolvedAt
    );

    if (existingAlert) return; // Don't create duplicate alerts

    const alertTitles = {
      'threshold_exceeded': `${sensor.name} - Threshold Exceeded`,
      'sensor_offline': `${sensor.name} - Sensor Offline`,
      'low_battery': `${sensor.name} - Low Battery`,
      'maintenance_required': `${sensor.name} - Maintenance Required`,
      'anomaly_detected': `${sensor.name} - Anomaly Detected`
    };

    const alertDescriptions = {
      'threshold_exceeded': `${sensor.type.replace('_', ' ')} reading of ${reading?.value}${reading?.unit} exceeds ${severity === 'critical' ? 'critical' : 'warning'} threshold`,
      'sensor_offline': `Sensor has not reported data for over 10 minutes`,
      'low_battery': `Battery level is ${sensor.batteryLevel}%`,
      'maintenance_required': `Sensor requires calibration - last calibrated over 90 days ago`,
      'anomaly_detected': `Unusual reading pattern detected`
    };

    const alert: IoTAlert = {
      id: `alert_${Date.now()}_${sensor.id}`,
      sensorId: sensor.id,
      sensor,
      type,
      severity,
      title: alertTitles[type],
      description: alertDescriptions[type],
      reading,
      createdAt: new Date(),
      autoGenerated: true
    };

    this.alerts.push(alert);

    // Auto-generate civic report for critical issues
    if (severity === 'critical' && type === 'threshold_exceeded') {
      this.autoGenerateCivicReport(alert);
    }

    console.log(`IoT Alert: ${alert.title} - ${alert.description}`);
  }

  private async autoGenerateCivicReport(alert: IoTAlert) {
    // This would integrate with your existing report creation system
    const reportData = {
      title: `Automated Report: ${alert.title}`,
      description: `${alert.description}\n\nThis report was automatically generated by IoT sensor monitoring system.\n\nSensor Details:\n- Location: ${alert.sensor.location.address}\n- Last Reading: ${alert.reading?.value}${alert.reading?.unit}\n- Time: ${alert.createdAt.toLocaleString()}`,
      category: this.mapSensorTypeToCategory(alert.sensor.type),
      priority: 'urgent',
      location: {
        address: alert.sensor.location.address,
        coordinates: {
          lat: alert.sensor.location.lat,
          lng: alert.sensor.location.lng
        }
      },
      automated: true,
      iotAlertId: alert.id
    };

    try {
      // This would call your existing API to create a report
      console.log('Auto-generating civic report:', reportData);
      alert.reportId = `auto_${Date.now()}`;
    } catch (error) {
      console.error('Failed to auto-generate civic report:', error);
    }
  }

  private mapSensorTypeToCategory(sensorType: string): string {
    const mapping = {
      'air_quality': 'Infrastructure',
      'noise_level': 'Other',
      'traffic_flow': 'Traffic',
      'waste_bin': 'Waste Management',
      'street_light': 'Lighting',
      'water_level': 'Water & Utilities',
      'weather': 'Other',
      'parking': 'Traffic',
      'crowd_density': 'Other'
    };
    return mapping[sensorType] || 'Other';
  }

  public getSensors(): IoTSensor[] {
    return Array.from(this.sensors.values());
  }

  public getSensor(sensorId: string): IoTSensor | undefined {
    return this.sensors.get(sensorId);
  }

  public getSensorReadings(sensorId: string, limit: number = 100): SensorReading[] {
    const readings = this.readings.get(sensorId) || [];
    return readings.slice(-limit);
  }

  public getAlerts(resolved: boolean = false): IoTAlert[] {
    return this.alerts.filter(alert => resolved ? alert.resolvedAt : !alert.resolvedAt);
  }

  public resolveAlert(alertId: string): boolean {
    const alert = this.alerts.find(a => a.id === alertId);
    if (alert && !alert.resolvedAt) {
      alert.resolvedAt = new Date();
      return true;
    }
    return false;
  }

  public getSmartCityDashboard(): SmartCityDashboard {
    const airQualityReadings = this.getLatestReadingsByType('air_quality');
    const noiseReadings = this.getLatestReadingsByType('noise_level');
    const trafficReadings = this.getLatestReadingsByType('traffic_flow');
    const wasteReadings = this.getLatestReadingsByType('waste_bin');
    const lightReadings = this.getLatestReadingsByType('street_light');
    const waterReadings = this.getLatestReadingsByType('water_level');

    const sensorStats = this.getSensorHealthStats();

    return {
      airQualityIndex: this.calculateAverage(airQualityReadings),
      noiseLevel: this.calculateAverage(noiseReadings),
      trafficFlow: this.calculateAverage(trafficReadings),
      waterLevels: waterReadings,
      wasteCapacity: this.calculateAverage(wasteReadings),
      streetLightStatus: this.calculateAverage(lightReadings),
      weatherData: {
        temperature: 28.5 + Math.random() * 5,
        humidity: 65 + Math.random() * 15,
        windSpeed: 5 + Math.random() * 10,
        rainfall: Math.random() * 2
      },
      alerts: this.getAlerts().slice(0, 10),
      sensorHealth: sensorStats
    };
  }

  private getLatestReadingsByType(sensorType: string): number[] {
    const sensorsOfType = Array.from(this.sensors.values()).filter(s => s.type === sensorType);
    return sensorsOfType.map(sensor => {
      const readings = this.readings.get(sensor.id) || [];
      const latest = readings[readings.length - 1];
      return latest ? latest.value : 0;
    });
  }

  private calculateAverage(values: number[]): number {
    if (values.length === 0) return 0;
    return values.reduce((sum, val) => sum + val, 0) / values.length;
  }

  private getSensorHealthStats() {
    const sensors = Array.from(this.sensors.values());
    const stats = {
      active: sensors.filter(s => s.status === 'active').length,
      inactive: sensors.filter(s => s.status === 'inactive').length,
      maintenance: sensors.filter(s => s.status === 'maintenance').length,
      total: sensors.length
    };
    return stats;
  }

  public getPredictiveInsights(): PredictiveModel[] {
    return Array.from(this.predictiveModels.values());
  }

  public getSensorsByZone(zone: string): IoTSensor[] {
    return Array.from(this.sensors.values()).filter(sensor => sensor.location.zone === zone);
  }

  public getEnvironmentalIndex(): {
    score: number;
    grade: 'A' | 'B' | 'C' | 'D' | 'F';
    factors: { name: string; score: number; impact: number }[];
  } {
    const airQualityAvg = this.calculateAverage(this.getLatestReadingsByType('air_quality'));
    const noiseAvg = this.calculateAverage(this.getLatestReadingsByType('noise_level'));
    const wasteAvg = this.calculateAverage(this.getLatestReadingsByType('waste_bin'));

    const factors = [
      { name: 'Air Quality', score: Math.max(0, 100 - airQualityAvg), impact: 0.4 },
      { name: 'Noise Levels', score: Math.max(0, 100 - noiseAvg), impact: 0.3 },
      { name: 'Waste Management', score: Math.max(0, 100 - wasteAvg), impact: 0.3 }
    ];

    const totalScore = factors.reduce((sum, factor) => sum + (factor.score * factor.impact), 0);
    
    let grade: 'A' | 'B' | 'C' | 'D' | 'F';
    if (totalScore >= 90) grade = 'A';
    else if (totalScore >= 80) grade = 'B';
    else if (totalScore >= 70) grade = 'C';
    else if (totalScore >= 60) grade = 'D';
    else grade = 'F';

    return { score: totalScore, grade, factors };
  }

  public connectWebSocket(url: string = 'ws://localhost:8080/iot') {
    try {
      this.websocket = new WebSocket(url);
      
      this.websocket.onopen = () => {
        this.isConnected = true;
        console.log('IoT WebSocket connected');
      };

      this.websocket.onmessage = (event) => {
        try {
          const data = JSON.parse(event.data);
          this.handleWebSocketMessage(data);
        } catch (error) {
          console.error('Failed to parse WebSocket message:', error);
        }
      };

      this.websocket.onclose = () => {
        this.isConnected = false;
        console.log('IoT WebSocket disconnected');
        // Attempt to reconnect after 5 seconds
        setTimeout(() => this.connectWebSocket(url), 5000);
      };

      this.websocket.onerror = (error) => {
        console.error('IoT WebSocket error:', error);
      };
    } catch (error) {
      console.error('Failed to connect to IoT WebSocket:', error);
    }
  }

  private handleWebSocketMessage(data: any) {
    switch (data.type) {
      case 'sensor_reading':
        this.addSensorReading(data.sensorId, data.reading);
        break;
      case 'sensor_status':
        this.updateSensorStatus(data.sensorId, data.status);
        break;
      case 'new_sensor':
        this.sensors.set(data.sensor.id, data.sensor);
        break;
      case 'alert':
        this.alerts.push(data.alert);
        break;
      default:
        console.log('Unknown IoT message type:', data.type);
    }
  }

  private updateSensorStatus(sensorId: string, status: IoTSensor['status']) {
    const sensor = this.sensors.get(sensorId);
    if (sensor) {
      sensor.status = status;
    }
  }

  public sendCommand(sensorId: string, command: string, parameters: any = {}) {
    if (!this.isConnected || !this.websocket) {
      console.error('WebSocket not connected');
      return false;
    }

    const message = {
      type: 'command',
      sensorId,
      command,
      parameters,
      timestamp: new Date().toISOString()
    };

    this.websocket.send(JSON.stringify(message));
    return true;
  }

  public calibrateSensor(sensorId: string) {
    const sensor = this.sensors.get(sensorId);
    if (sensor) {
      sensor.calibrationDate = new Date();
      sensor.status = 'maintenance';
      
      // Send calibration command
      this.sendCommand(sensorId, 'calibrate');
      
      // Simulate calibration completion after 30 seconds
      setTimeout(() => {
        sensor.status = 'active';
        console.log(`Sensor ${sensorId} calibration completed`);
      }, 30000);
      
      return true;
    }
    return false;
  }

  public getDataExport(sensorIds: string[], startDate: Date, endDate: Date) {
    const exportData = {
      metadata: {
        exportDate: new Date(),
        startDate,
        endDate,
        sensorCount: sensorIds.length
      },
      sensors: sensorIds.map(id => this.sensors.get(id)).filter(Boolean),
      readings: sensorIds.map(sensorId => ({
        sensorId,
        readings: (this.readings.get(sensorId) || []).filter(reading => 
          reading.timestamp >= startDate && reading.timestamp <= endDate
        )
      }))
    };

    return exportData;
  }
}

export const iotService = new IoTIntegrationService();
export default iotService;